name: Build Nginx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        sudo apt-get update
        # sudo apt-get install -y build-essential libpcre3-dev zlib1g-dev openssl libssl-dev libgeoip-dev libgd-dev

    - name: Download Nginx source
      run: |
        wget https://www.openssl.org/source/openssl-3.3.0.tar.gz
        wget https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.40/pcre2-10.40.tar.gz
        wget https://zlib.net/zlib-1.3.1.tar.gz
        wget http://nginx.org/download/nginx-1.26.1.tar.gz

        tar -xzvf openssl-3.3.0.tar.gz
        tar -xzvf pcre2-10.40.tar.gz
        tar -xzvf zlib-1.3.1.tar.gz
        tar -xzvf nginx-1.26.1.tar.gz
        cd nginx-1.26.1

    - name: Configure and build Nginx
      run: |
        cd nginx-1.26.1
        pwd
        ./configure --with-openssl=../openssl-3.3.0 --with-pcre=../pcre2-10.40 --with-zlib=../zlib-1.3.1 --with-pcre-jit --user=root --prefix=../nginx --with-http_ssl_module --with-http_v2_module
        make
        make install # Optional, depending on your needs

    - name: Test Nginx
      run: |
        # Add any tests you need here
        echo "Tests would go here"

    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: nginx-1.26.1
        path: /home/runner/work/nginx-binary/nginx-binary/nginx # or wherever the built files are located

    - name: Other post-build steps
      run: |
        # Any other steps after the build process
        echo "Post-build steps here"