name: Build Nginx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: centos7-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpcre3-dev zlib1g-dev openssl libssl-dev libgeoip-dev libgd-dev

    - name: Download Nginx source
      run: |
        wget http://nginx.org/download/nginx-${{ matrix.nginx-version }}.tar.gz
        tar -xzvf nginx-${{ matrix.nginx-version }}.tar.gz
        cd nginx-${{ matrix.nginx-version }}

    - name: Configure and build Nginx
      run: |
        ./configure --prefix=/usr/local/nginx
        make
        make install # Optional, depending on your needs

    - name: Test Nginx
      run: |
        # Add any tests you need here
        echo "Tests would go here"

    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: nginx-build
        path: /usr/local/nginx # or wherever the built files are located

    - name: Other post-build steps
      run: |
        # Any other steps after the build process
        echo "Post-build steps here"