name: Build Nginx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpcre3-dev zlib1g-dev openssl libssl-dev libgeoip-dev libgd-dev

    - name: Download Nginx source
      run: |
        wget http://nginx.org/download/nginx-1.26.1.tar.gz
        tar -xzvf nginx-1.26.1.tar.gz
        cd nginx-1.26.1

    - name: Configure and build Nginx
      run: |
        cd nginx-1.26.1
        ls
        ./configure --prefix=../../nginx-1.26.1
        make
        make install # Optional, depending on your needs

    - name: Test Nginx
      run: |
        # Add any tests you need here
        echo "Tests would go here"

    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: nginx-build
        path: ../../nginx-1.26.1 # or wherever the built files are located

    - name: Other post-build steps
      run: |
        # Any other steps after the build process
        echo "Post-build steps here"